name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy locally on EC2
        run: |
          cd ~/OCR-Implementez_un_modele_de_scoring/app

          git fetch origin
          git reset --hard origin/main

          docker stop scoring-container || true
          docker rm scoring-container || true

          docker build -t scoring-app .

          docker run -d \
            --name scoring-container \
            --restart always \
            -p 8501:8501 \
            -p 8000:8000 \
            scoring-app